package enums;

public enum Sides {
LEFT_WEEK ,LEFT_HARD,UP,DOWN,RIGHT_WEEK,RIGHT_HARD,DO_NOTHING,LEFT,RIGHT,
C_LEFT,C_RIGHT,NORMAL_PAD,FIRE_PAD,NORMAL_TARGET,MOVING_TARGET,GUN_TARGET,NO_HIT,BOLET_LOADED,BOLET_FIRED,BOLET_DONE
,PAD_FIRE,STOP_FIRE,CHANGE_TARGET_COLOR,GAME_NORMAL,GAME_WON_LEVEL;
};
